/**************************************************************************
 * Copyright (C) 2012-2021  Unisound
 *
 * DO NOT MODIFY.
 *
 * This file was generated by res_build_tool.py
 *
 **************************************************************************/
#ifndef __UNI_CUST_CONFIG_H__
#define __UNI_CUST_CONFIG_H__

#define UNI_ASR_TIMEOUT           10    //ASR timeout Xs

#define UNI_MIC_ARRY_TYPE_LINER   0
#define UNI_MIC_ARRY_TYPE_CIRCLE  1
#define ACOUSTIC_MODEL_FIELD_NEAR 0
#define ACOUSTIC_MODEL_FIELD_FAR  1

#define KWS_WAKEUP_SCORE_THRED    (-2.52)
#define KWS_SLEEP_SCORE_THRED    (-1.14)
#define KWS_CMD_SCORE_THRED       (-1.59)
#define KWS_HASHTABLE_SIZE        (5)

/*---MIC config---*/
#define ACOUSTIC_MODEL_FIELD  ACOUSTIC_MODEL_FIELD_FAR
#define UNI_MIC_ARRY_NUM          1

#define LOCAL_TONE_MAX_VOLUME      "[101]"
#define LOCAL_TONE_MIN_VOLUME      "[102]"
#define DEFAULT_PCM_WAKEUP        "[103, 104, 105]"
#define DEFAULT_PCM_ASR_TIMEOUT   "[106]"
#define DEFAULT_PCM_SLEEP         "[106]"
#define DEFAULT_PCM_WELCOME       "[1]"

#endif /*__UNI_CUST_CONFIG_H__*/
