includes += \
	-I$(ROOT)/apps/$(APP_CASE)/smartbox/unisound/ \

objs += \
		$(ROOT)/apps/$(APP_CASE)/smartbox/unisound/kws_demo.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/unisound/uni_json.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/unisound/uni_lasr_result_parser.o \
		$(ROOT)/apps/$(APP_CASE)/smartbox/unisound/uni_nlu.o \
		
include $(ROOT)/apps/$(APP_CASE)/smartbox/unisound/user/Makefile